### ISSUE TITLE
Not receiving emails for code discussions

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1361]
Here's an example of a code discussion thread that I did not get notified of: https://sourcegraph.com/github.com/sourcegraph/lang-go/-/blob/src/lspext.ts#L394-395&tab=discussions&threadID=157

Does it matter whether or not I have the extension enabled?

**Comment by slimsag** [comment]
ack, prod does not have email configured for some reason. I don't know why. It must be that the configuration was reset to an old version somehow? Will fix.

**Comment by felixfbecker** [comment]
I just got one for a reply, seems fixed

**Comment by slimsag** [comment]
> Does it matter whether or not I have the extension enabled?

@chrismwendt It does not.

**Comment by slimsag** [comment]
I think notifications should be working now, but replies will not yet because imap is not configured. Will fix.

**Comment by felixfbecker** [comment]
I've been pinging people in various comments over the past 2 months (one just yesterday) and they say they did not get any notifications, so this issue still seems to exist. This makes me really uncomfortable using code discussions.

cc @sqs

**Comment by slimsag** [comment]
I investigated.

Dogfood was entirely reset, so everything there is gone. That includes all past code discussions, but also our entire email configuration which means dogfood cannot send email notifications even for e.g. saved searches (apparently nobody dogfoods these). I have added back the missing email config, but suggest **don't do anything on dogfood that you want to be persistent (including code discussions) as we seem to drop its data every few months.**

Sourcegraph.com's configuration was fine (but was missing `email.imap` which would've prevented reply-by-email-response from working). The actual cause is a panic due to us apparently pulling in docsite/markdown into this repository, which is an awful thing to do IMO, but a separate problem I will follow up on:

```
goroutine panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1369821 [running]:
runtime/debug.Stack(0xc000a416a8, 0x152cc40, 0x35e2150)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine.Go.func1.1()
	/buildkite/builds/buildkite-agent-67c6944878-6kgpj-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine/goroutine.go:20 +0x5a
panic(0x152cc40, 0x35e2150)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/sourcegraph/docsite/markdown.getTitle(0xc0349a5180, 0x0, 0x0)
	/buildkite/builds/buildkite-agent-67c6944878-6kgpj-1/sourcegraph/.golang/sourcegraph/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190215213424-0f45ee5daab5/markdown/markdown.go:237 +0x2c
github.com/sourcegraph/docsite/markdown.Run(0x28f1840, 0xc0000ca010, 0x3660148, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/buildkite/builds/buildkite-agent-67c6944878-6kgpj-1/sourcegraph/.golang/sourcegraph/pkg/mod/github.com/sourcegraph/docsite@v0.0.0-20190215213424-0f45ee5daab5/markdown/markdown.go:108 +0x446
github.com/sourcegraph/sourcegraph/pkg/markdown.Render(0x0, 0x0, 0x0, 0xc00000000d, 0xc004f098c0, 0x0, 0x0)
	/buildkite/builds/buildkite-agent-67c6944878-6kgpj-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/pkg/markdown/markdown.go:26 +0xc7
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/pkg/discussions.(*notifier).notifyUsername(0xc0358c13b0, 0x28f1840, 0xc0000ca010, 0xc006f84b21, 0x3, 0x2, 0x0)
	/buildkite/builds/buildkite-agent-67c6944878-6kgpj-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/pkg/discussions/notify_mentions.go:250 +0x40e
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/pkg/discussions.notifyMentions.func1()
	/buildkite/builds/buildkite-agent-67c6944878-6kgpj-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/pkg/discussions/notify_mentions.go:59 +0x155
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine.Go.func1(0xc038bb47d0)
	/buildkite/builds/buildkite-agent-67c6944878-6kgpj-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine/goroutine.go:24 +0x43
created by github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine.Go
	/buildkite/builds/buildkite-agent-67c6944878-6kgpj-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/goroutine/goroutine.go:17 +0x3f
```

So, yeah, regression.

**Comment by slimsag** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/2369
