### ISSUE TITLE
Fix 404s in docs and in repo READMEs

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1515]
A user @P3GLEG reported that our docs and various repository READMEs have many broken links. We need to have an automated way to identify and prevent these errors.

- [x] Identify and fix all current 404s in doc pages
- [x] Identify and fix all current 404s in repository READMEs
- [x] Identify and fix all current 404s otherwise in our repositories (e.g., in comments, in blog posts, etc.)
- [ ] Monitor all of those sources continuously for regressions (links becoming 404s)

**Comment by P3GLEG** [comment]
Here is a file with the 404's I found today. It was automated so there is stuff to ignore. I cloned repos for the last 2 weeks and regexed through them for urls related to sourcegraph.com then requested them. 

The CSV is attached and separated by "," and multiple filenames are separated by "||"
[badurls.txt](https://github.com/sourcegraph/sourcegraph/files/2697674/badurls.txt)

**Comment by P3GLEG** [comment]
Here's the ugly script to do it
`import requests
import re
import glob
import os
from urllib.parse import urlparse

results = {}
for filename in glob.iglob('./**/*', recursive=True):
    if os.path.isfile(filename):
        with open(filename) as f:
            try:
                urls = re.findall(r'''(?i)\b((?:https?:(?:/{1,3}|[a-z0-9%])|[a-z0-9.\-]+[.](?:com)/)(?:[^\s()<>{}\[\]]+|\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\))+(?:\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\)|[^\s`!()\[\]{};:'".,<>?«»""''])|(?:(?<!@)[a-z0-9]+(?:[.\-][a-z0-9]+)*[.](?:com)\b/?(?!@)))''', f.read())
                for url in urls:
                    url = url.split('?')[0].split('#')[0]
                    if url not in results:
                        results[url] = []
                    results[url].append(filename)
            except Exception as e:
                pass

for url,filenames in results.items():
    try:
        parsed = urlparse(url)
        if 'sourcegraph.com' in parsed.netloc and not any(i in url for i in ['/api/console', '/search']):
            resp = requests.get(url)
            if resp.status_code == 404:
                f.write(f'{url},{"||".join(filenames)}\n')
    except:
        pass
`

**Comment by sqs** [comment]
I have fixed all known instances of these that I identified with my own scripts. I also added a check for broken internal links in CI for docs. I will (after 3.0) set up other monitoring to prevent reoccurrences.

**Comment by nicksnyder** [comment]
@ryan-blunden What are the action items here? If you aren't going to work on this, or if there is unclear next steps here, then backlog or close

**Comment by ryan-blunden** [comment]
I've reviewed this and Quinn has fixed the vast majority of broken links.

Moving this to the 3.3 milestone as the links that are still broken must be very few.

**Comment by sqs** [comment]
BTW, monitoring for broken links would be a great product feature for saved searches
