### ISSUE TITLE
Cannot read property 'sync' of undefined.

### ISSUE THREAD

**Issue by ianseyer** [sourcegraph/sourcegraph#15363]
Shortly after upgrading Sourcegraph to `3.20`, our bitbucket integration has broken; it fails on bitbucket with:

```
integration.bundle.js:1 Uncaught TypeError: Cannot read property 'sync' of undefined
    at f (integration.bundle.js:1)
    at f (integration.bundle.js:20689)
    at p (integration.bundle.js:20689)
    at Su (integration.bundle.js:30573)
    at s (integration.bundle.js:47217)
    at integration.bundle.js:47217
    at Module.<anonymous> (integration.bundle.js:47217)
    at n (integration.bundle.js:1)
    at Object.<anonymous> (integration.bundle.js:47217)
    at n (integration.bundle.js:1)
```

I am running the latest version of the plugin (pulled directly from `latest.jar`).

While I am not convinced it is because of the upgrade, it is the only real change that has been made to our setup.

I see before the error:

```
Sourcegraph native integration is running
integration.bundle.js:47217 Detected code host: bitbucket-server
```

And the auth token is successfully used.

**Comment by christinelovett** [comment]
https://app.hubspot.com/contacts/2762526/company/623971957

**Comment by felixfbecker** [comment]
This should be fixed by https://github.com/sourcegraph/sourcegraph/pull/15414, right @tjkandala ? (unreleased)

**Comment by felixfbecker** [comment]
@marekweb @tjkandala this is fixed in `main`, right? Was this released in some version? Could you 
 close the issue if fixed in `main` and comment what release this was/will be released in? 🙂

**Comment by marekweb** [comment]
This has been fixed in the 3.22 release of Sourcegraph.

**Comment by ianseyer** [comment]
@marekweb Completed an upgrade of 3.22 and the same issue persists. Have reinstalled the plugin on the bitbucket side to no avail.
