### ISSUE TITLE
Starting Sourcegraph with SOURCEGRAPHDOTCOM_MODE=true is broken

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#18151]
#### Steps to reproduce:

1. Run `env SOURCEGRAPHDOTCOM_MODE=true ./enterprise/dev/start.sh`

#### Expected behavior:

Sourcegraph runs normally with SOURCEGRAPHDOTCOM_MODE flag set to true, allowing testing and debugging of Cloud-only features

#### Actual behavior:

Staring Sourcegraph terminates. (There is a workaround by also running with flag `SRC_DISABLE_PROFILER=true` and going into the database table `external_services` and setting `cloud_default` to true to both a GitHub and a GitLab service)

Example error log:

```
$ env SOURCEGRAPHDOTCOM_MODE=true ./enterprise/dev/start.sh
19:15:15 ctags-image | Building ctags docker image
19:15:15 ctags-image | Terminating ctags-image
19:15:15  go-install | Go race detector disabled. You can enable it for specific commands by setting GORACED (e.g. GORACED=frontend,searcher or GORACED=all for all commands)
19:15:16        yarn | warning Resolution field "history@4.5.1" is incompatible with requested version "history@^4.9.0"
19:15:16        yarn | warning Resolution field "history@4.5.1" is incompatible with requested version "history@^4.9.0"
19:15:17        yarn | Terminating yarn
19:15:22  go-install | Terminating go-install
--- Starting all binaries...
19:15:22                  keycloak | Not using Keycloak. Keycloak authentication providers will not work.
19:15:22                  keycloak | Terminating keycloak
19:15:22              github-proxy | INFO github-proxy: listening, addr: 127.0.0.1:3180
19:15:22         postgres_exporter | Building pg_exporter docker image
19:15:22        codeintel-executor | INFO Connecting to Sourcegraph instance, url: http://localhost:3080
19:15:22                 gitserver | 2021/02/10 03:15:22 failed to start profiler: project ID must be specified in the configuration if running outside of GCP
19:15:22                 gitserver | Terminating gitserver
19:15:22              query-runner | Terminating query-runner
19:15:22              repo-updater | Terminating repo-updater
19:15:22                     caddy | {"level":"info","ts":1612926922.4958122,"msg":"using provided configuration","config_file":"dev/Caddyfile","config_adapter":""}
19:15:22                   docsite | # Doc site is available at http://localhost:5080
19:15:22                     caddy | {"level":"info","ts":1612926922.499904,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
19:15:22                     caddy | 2021/02/09 19:15:22 [INFO][cache:0xc00075c7d0] Started certificate maintenance routine
19:15:22                     caddy | {"level":"info","ts":1612926922.510875,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
19:15:22                     caddy | {"level":"info","ts":1612926922.511824,"logger":"tls","msg":"cleaned up storage units"}
19:15:22                     caddy | {"level":"info","ts":1612926922.5119748,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["sourcegraph.test"]}
19:15:22                     caddy | 2021/02/09 19:15:22 [WARNING] Stapling OCSP: no OCSP stapling for [sourcegraph.test]: no OCSP server specified in certificate
19:15:22                  searcher | Terminating searcher
19:15:22                   symbols | Terminating symbols
19:15:22              github-proxy | Terminating github-proxy
19:15:22                  frontend | Terminating frontend
19:15:22       zoekt-indexserver-0 | 2021/02/09 19:15:22 tmpfriend: Removing /Users/julip/.sourcegraph/zoekt/index-0/.indexserver.tmp/tmpfriend-66765-326710176
19:15:22                     watch | Terminating watch
19:15:22                     nginx | Terminating nginx
19:15:22                     caddy | {"level":"info","ts":1612926922.584219,"msg":"shutting down","signal":"SIGINT"}
19:15:22       zoekt-indexserver-1 | 2021/02/09 19:15:22 tmpfriend: Removing /Users/julip/.sourcegraph/zoekt/index-1/.indexserver.tmp/tmpfriend-66738-911926233
19:15:22                     caddy | {"level":"warn","ts":1612926922.667676,"logger":"pki.ca.local","msg":"installing root certificate (you might be prompted for password)","path":"storage:pki/authorities/local/root.crt"}
19:15:22           codeinsights-db | codeinsights-db: building sourcegraph/codeinsights-db:dev...
19:15:22                     caddy | 2021/02/09 19:15:22 define JAVA_HOME environment variable to use the Java trust
19:15:22                prometheus | Prometheus: building sourcegraph/prometheus:dev...
19:15:22                   grafana | Grafana: building sourcegraph/grafana:dev...
19:15:22         zoekt-webserver-0 | 2021/02/09 19:15:22 loading 61 shards
19:15:22         zoekt-webserver-1 | 2021/02/09 19:15:22 loading 84 shards
19:15:23            syntect_server | syntect_server
19:15:23           codeinsights-db | codeinsights-db: serving on http://localhost:5435
19:15:23           codeinsights-db | codeinsights-db: note that logs are piped to /Users/julip/.sourcegraph-dev/logs/codeinsights-db/codeinsights-db.log
19:15:23         postgres_exporter | time="2021-02-10T03:15:23Z" level=info msg="Established new database connection to \"host.docker.internal:5432\"." source="postgres_exporter.go:814"
19:15:23         postgres_exporter | time="2021-02-10T03:15:23Z" level=info msg="Semantic Version Changed on \"host.docker.internal:5432\": 0.0.0 -> 12.3.0" source="postgres_exporter.go:1335"
19:15:23            syntect_server | 2021/02/10 03:15:23 worker command: env ROCKET_PORT={{.Port}} /syntect_server
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12: started on port 41767
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12: Configured for production.
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12:     => address: 0.0.0.0
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12:     => port: 41767
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12:     => log: critical
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12:     => workers: 16
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12:     => secret key: provided
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12:     => limits: forms = 32KiB, json* = 10MiB
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12:     => keep-alive: disabled
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12:     => tls: disabled
19:15:23            syntect_server | 2021/02/10 03:15:23 worker 12: Rocket has launched from http://0.0.0.0:41767
19:15:23         postgres_exporter | time="2021-02-10T03:15:23Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1576"
19:15:24                     caddy | 2021/02/09 19:15:24 certificate installed properly in NSS security databases
19:15:25                   grafana | Grafana: serving on http://localhost:3370
19:15:25                   grafana | Grafana: note that logs are piped to /Users/julip/.sourcegraph-dev/logs/grafana/grafana.log
19:15:31                prometheus | Prometheus: serving on http://localhost:9090
19:15:31                prometheus | Prometheus: note that logs are piped to /Users/julip/.sourcegraph-dev/logs/prometheus/prometheus.log
19:15:32                     caddy | Terminating caddy
Password:
19:15:32                       web | Terminating web
19:15:32            syntect_server | Terminating syntect_server
19:15:32       zoekt-indexserver-0 | Terminating zoekt-indexserver-0
19:15:32       zoekt-indexserver-1 | Terminating zoekt-indexserver-1
19:15:32         zoekt-webserver-0 | 2021/02/09 19:15:32 shutting down
19:15:32         zoekt-webserver-0 | Terminating zoekt-webserver-0
19:15:32         zoekt-webserver-1 | 2021/02/09 19:15:32 shutting down
19:15:32         zoekt-webserver-1 | Terminating zoekt-webserver-1
19:15:33           codeinsights-db | Terminating codeinsights-db
19:15:33                    jaeger | Terminating jaeger
19:15:33                   docsite | Terminating docsite
19:15:33                prometheus | Terminating prometheus
19:15:33                   grafana | Terminating grafana
19:15:33         postgres_exporter | Terminating postgres_exporter
19:15:33            executor-queue | Terminating executor-queue
19:15:33        codeintel-executor | ERROR Signal received while connecting to Sourcegraph
19:15:33        codeintel-executor | Terminating codeintel-executor
19:15:33 precise-code-intel-worker | Terminating precise-code-intel-worker
19:15:33                     minio | Terminating minio
goreman: exit status 1
```

**Comment by ryanslade** [comment]
@limitedmage This should be fixed now.

You'll need to be on latest `main` for https://github.com/sourcegraph/sourcegraph and `master` for https://github.com/sourcegraph/dev-private

**Comment by limitedmage** [comment]
This is not fixed for me. I still have to add `SRC_DISABLE_PROFILER=true` to make `SOURCEGRAPHDOTCOM_MODE=true` work.  Otherwise, I get this error:

```
--------------------------------------------------------------------------------
Failed to run gitserver:
Exit code: 1

Standard out:

Standard err:
        2021/09/07 16:18:33 failed to start profiler: project ID must be specified in the configuration if running outside of GCP

--------------------------------------------------------------------------------
error: failed to run gitserver
```

**Comment by limitedmage** [comment]
(Actually, using `start.sh` works but not `sg start`).
