### ISSUE TITLE
Update CodeCov + Snyk to be tagged "insights"

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#21262]
We should make sure they both show up here: https://sourcegraph.com/extensions?query=category%3AInsights&category=All since that's linked directly from our "get insights extensions" flow setup. 

Just a quick edit and republish.

**Comment by vovakulikov** [comment]
@felixfbecker or @tjkandala can you help me with access to these repos
When I tried to push a new branch but it seems like I don't have an access to codecov and snyk extensions repos

```
ERROR: Permission to codecov/sourcegraph-codecov.git denied to vovakulikov.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by felixfbecker** [comment]
Done :)

**Comment by vovakulikov** [comment]
@felixfbecker I was able to push changes to snyk repo, thanks. But still have a problem with codecov. I assume that because our codecov extension repo is stored under the codecov org and I don't have an access to codecov org on github.

**Comment by felixfbecker** [comment]
@vovakulikov I had sent you an invite to Codecov too – please check your email, you probably need to accept it first.

![image](https://user-images.githubusercontent.com/10532611/121936868-5b6bd680-cd4a-11eb-9837-47adf4cd6f96.png)
