### ISSUE TITLE
docs.sourcegraph.com tells me to use an outdated Sourcegraph version

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2708]
1. Visit https://docs.sourcegraph.com/
2. **Be confused:** I am on `3.2 (next)` but the docker command is for running 3.1.2..
3. Click `3.1 (current)` ("Why isn't the current version selected by default?")
4. **Be more confused**: The docker run command is for 3.0.1! "I selected 3.1, WTF is going on?!"
5. Run the command, get notified you should update once Sourcegraph runs... etc.

**Comment by slimsag** [comment]
Note: This is despite the fact that the versions in our doc/ template are accurate: 

https://github.com/sourcegraph/sourcegraph/blob/7d195c8cbebe53381691812f13300d87c321bab3/doc/_resources/templates/doc.html#L32-L35

**Comment by sqs** [comment]
Oh, I need to make docs.sourcegraph.com deploy from those files. I have an unmerged PR with that in deploy-Sourcegraph-dot-com, will merge tonight.

**Comment by sqs** [comment]
Also related #1788

**Comment by sqs** [comment]
@ryan-blunden 	This is related to #1788 	and https://github.com/sourcegraph/sourcegraph/issues/2481, both of which are assigned to you for 3.2.  Therefore reassigning this issue to you. (I merged the last bit of my work to migrate docs.sourcegraph.com templates/assets into this repo in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/402, so https://docs.sourcegraph.com is now reading templates, assets, and doc contents from this repo.)

**Comment by ryan-blunden** [comment]
Fixed by #2481

**Comment by nicksnyder** [comment]
This is not fixed yet

![Screen Shot 2019-03-20 at 10 24 34 AM](https://user-images.githubusercontent.com/754768/54705601-6e0aed00-4afa-11e9-853f-9472b4ec58e3.png)

**Comment by ryan-blunden** [comment]
It was fixed with the docs version change - https://github.com/sourcegraph/sourcegraph/pull/2841/files#diff-3d0e70da24a04f44a1fdc404b7242b89

**Comment by nicksnyder** [comment]
@ryan-blunden I think you misunderstand the issue. If you click on the 3.2 link it has you install 3.1.2, which seems wrong. This is not fixed yet.

**Comment by ryan-blunden** [comment]
![ScreenFlow](https://user-images.githubusercontent.com/133014/54798778-68ef9000-4c17-11e9-976c-7da0daae94a0.gif)

It's fixed by applying the version content and template changes on the 3.2 and 3.1 branches, and then changing the breadcrumb links on the doc.html template on master to download the (updated) branch, not the tagged content.

Big thanks to @chrismwendt for brainstorming with me to come up with a great and fast solution.

I'll document and update the release checklist.
