### ISSUE TITLE
Getting started improvements

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#29890]
- [ ] Under the feature flag turn off the existing "GET STARTED" search tour that helps you search by language or repo

In user testing, diff search was observed to be slow, which is a bad first impression. Additionally, we are missing a key value proposition, which is searching multiple repositories. To solve this, we need to re-order the searches and replace the symbol search. These tasks should fix these issues:

- [ ] Move the diff search to the last search of the code search use cases
- [ ] Change the label for the diff search to: "Search diffs for removed code"
- [ ] Remove symbol search, replace with "Search multiple repos" which runs the this [search](https://sourcegraph.com/search?q=context:global+repo:linkedin+lang:java+AtomicBoolean&patternType=literal), place as first item in the code search category

Some users didn't understand the value proposition immediately.
- [ ] Add help dialogs we used on find references and diffs to help them understand the power of the feature. [Copy and examples here](https://www.figma.com/file/uq7yt5ETrrXiHjcb6dfHSi/Getting-started-checklist?node-id=593%3A25254). 
       
Quick survey showed that users want language-specific onboarding tour.
- [ ] Add languages support. [Figma designs & content](https://www.figma.com/file/uq7yt5ETrrXiHjcb6dfHSi/Getting-started-checklist?node-id=282%3A8933).
- [ ] Update any existing diff searches to the latest state of the search as listed in Figma

**Comment by erzhtor** [comment]
@rrhyne, can you, please, update all content/links in [Figma languages](https://www.figma.com/file/uq7yt5ETrrXiHjcb6dfHSi/Getting-started-checklist?node-id=282%3A8933)?

**Comment by rrhyne** [comment]
Done!

**Comment by erzhtor** [comment]
Hey @rrhyne , I still see "symbol search" links in all language examples, but you were requested to change it to (in the ticket description ☝️ ?

> Remove symbol search, replace with "Search multiple repos" which runs the this search, place as first item in the code search category

**Comment by rrhyne** [comment]
I noticed that over the weekend as well. Apologies! All the languages should have multi repo search instead of symbol and correct ordering now.
