### ISSUE TITLE
OCaml syntax highlighting is broken

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3545]
Syntax highlighting in OCaml files doesn't work, and instead falls back to plaintext rendering mode.

https://sourcegraph.com/github.com/facebook/infer@master/-/blob/infer/src/biabduction/SymExec.ml

https://sourcegraph.com/github.com/facebook/infer@master/-/blob/infer/src/biabduction/State.ml

https://sourcegraph.com/github.com/facebook/infer@master/-/blob/infer/src/biabduction/Match.ml

Reported by @rvantonder -- upgrading syntect will likely fix this for us.

Customers: https://app.hubspot.com/contacts/2762526/company/1871766314

**Comment by rvantonder** [comment]
Related issue, likely fixed in `v3.0.1` and up: https://github.com/trishume/syntect/issues/176

**Comment by rvantonder** [comment]
Bumping for visibility. Another example: https://sourcegraph.com/github.com/comby-tools/comby/-/blob/lib/pipeline/pipeline.ml#L31:8

Will dig into this soon.

**Comment by dadlerj** [comment]
Bump — just had this reported by https://app.hubspot.com/contacts/2762526/company/1749029033

Reproducible example: https://sourcegraph.com/github.com/xapi-project/xen-api@master/-/blob/ocaml/xapi/import.ml

**Comment by rvantonder** [comment]
The previous thread is stale. For the more current issue: @slimsag is there something I can do to help here? Last time I offered the answer was something along the lines of "it's tricky" :-)

**Comment by slimsag** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/10374 and will be in Sourcegraph 3.16.

![image](https://user-images.githubusercontent.com/3173176/80898171-51f1ed00-8cb5-11ea-82fc-1e7fada4a2fa.png)

**Comment by rvantonder** [comment]
Very excited to hear that OCaml support would be fixed :-) Unfortunately there still isn't highlighting for any of the links above on Sourcegraph.com. Does something still need to happen?

**Comment by slimsag** [comment]
@rvantonder fixed
