### ISSUE TITLE
Language extensions are not enabled upon instance start when there are no users yet

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#376]
If you start a fresh Sourcegraph instance (no users yet) with 1 or more entries in the `langservers` array in site config, the corresponding language extensions will not be enabled until you restart the server or change the site config.

The workaround is to add a dummy comment to site config and save the changes. This will trigger syncing of `langservers` from site config with global settings.

**Comment by slimsag** [comment]
@christmwendt IIRC this was fixed, yeah?

**Comment by slimsag** [comment]
@chrismwendt IIRC this was fixed, yeah?

**Comment by chrismwendt** [comment]
This is still a problem. The global settings start out as empty and aren't updated on instance start because there are no users available to edit the settings table with (`author_id` is a non-nullable column).

Here's a repro:

```bash
rm -rf ~/.sourcegraph
mkdir -p ~/.sourcegraph/config
cat > ~/.sourcegraph/config/sourcegraph-config.json <<EOF
{
  "auth.providers": [ { "type": "builtin" } ],
  "corsOrigin": "https://github.com",
  "appURL": "http://localhost:7080",
  "langservers": [
    { "address": "tcp://go:4389", "language": "go" }
  ]
}
EOF
docker run --publish 7080:7080 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph --volume /var/run/docker.sock:/var/run/docker.sock sourcegraph/server:2.12.0
```

**Comment by sqs** [comment]
This property is being removed from site config for 3.0, so we will not actually fix this. Closing.
