### ISSUE TITLE
Nicer display of sign-in errors

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3765]
When a user's sign-in fails, they are shown a text/plain page with a message like:

```
No user exists matching any of the verified emails: alice@example.com alice2@example.org.

First error was: Username "alice" already exists, but no verified email matched "alice@example.com"
```

Reported by a user from https://app.hubspot.com/contacts/2762526/company/407948923 on Sourcegraph.com, not on their internal instance

**Comment by keegancsmith** [comment]
We are doing our 3.13 triaging. @sourcegraph/web is there anything you need from the @sourcegraph/core-services team to accomplish this?

**Comment by felixfbecker** [comment]
It seems like currently web has no control over this page at all as it is returned straight from the backend - so yes. Is this something the web team should do in 3.13 iteration?

**Comment by keegancsmith** [comment]
I have no idea on relative prioritisation. Updating the backend to redirect into the app should be a one line change :) I imagine the bulk of the work is on the TS side.

**Comment by tsenart** [comment]
@lguychard: I removed the `team/core-services` label since most of the work here is web.

**Comment by rrhyne** [comment]
This issue appears to have been addressed.

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
I'm still seeing this issue in 3.30.3, and it would be nice to have it fixed.
