### ISSUE TITLE
GitLab OAuth certificate signed by unknown authority

### ISSUE THREAD

**Issue by Antoine98** [sourcegraph/sourcegraph#4652]
- **Sourcegraph version:** 3.5.0
- **Platform information:** redhat 7.6, Docker version 1.13.1, GitLab Community Edition 11.5.2, Gitlab https certificate with internal authority  

#### Steps to reproduce:

1. Setting Gitlab and sourcegraph  Oauth 
2. Try to Sign in with GitLab

#### Actual behavior:
Result is a blanck page with this line of error 
Post https://gitlab.intranet.xxx/oauth/token: x509: certificate signed by unknown authority

No errors in logs.

Is there a way to configure certificate in management console for gitlab oauth ? (like the option "certificate" in external service , GitLab projects )

Thank you

**Comment by MrRachelWong** [comment]
How are you configured?

**Comment by Antoine98** [comment]
**Management Console:**
{
  "externalURL": "https://sourcegraph.intranet.xxx",
  "auth.providers": [
    {
      "type": "builtin",
      "allowSignup": false
    },
    {
      "type": "gitlab",
      "displayName": "GitLab",
      "clientID": "xxxxxxxxxxxxx",
      "clientSecret": "xxxxxxxxxx",
      "url": "https://gitlab.intranet.xxx"
    }
  ]
}

**Gitlab Config:**

Callback URL | https://sourcegraph.intranet.xxx/.auth/gitlab/callback
-- | --
Trusted | Y
Scopes | **api** (Access the authenticated user's API)    **read_user** (Read the authenticated user's personal information)

**Comment by tsenart** [comment]
Has this been fixed? You should set the `certificate` field in your GitLab external service config: https://docs.sourcegraph.com/admin/external_service/gitlab#configuration

**Comment by Antoine98** [comment]
No i have the same error. now i have upgraded to version 3.11.0 
Certificate is set in external service it works to retreive project on gitlab but i think this parameter is never use with gitlab Oauth.

**Comment by tsenart** [comment]
Got it. This would indeed require us to support a `certificate` setting in the gitlab auth settings, like we do for the external service.

For future reference, we'd then have to ensure that the HTTP call that exchanges the token uses a custom `http.Client` that uses that certificate (like we do with the external service clients).

Specifically, HTTP requests that are handled by the returned [`gitlaboauth.CallbackHandler`](https://github.com/sourcegraph/sourcegraph/blob/04c08ef309e8e963540c74d89164103320829e5d/enterprise/cmd/frontend/auth/gitlaboauth/login.go#L23) need to somehow set the `http.Client` in the threaded `context.Context` with the [`HTTPClient` key](https://github.com/golang/oauth2/blob/858c2ad4c8b6c5d10852cb89079f6ca1c7309787/oauth2.go#L330). 

cc @beyang

**Comment by keegancsmith** [comment]
Related to #71

**Comment by keegancsmith** [comment]
The oauth2 library used by everyone has no nice way of injecting a different http client. It passes down the client to use via context values... In some places it will just create a http.Client with a custom oauth2.Transport, otherwise it will just use http.DefaultClient.

Essentially we need a concrete `*http.Client` and anywhere we call into oauth2 we need to ensure we have an appropriate ctx:

```go
httpClient := anExternalHTTPClient
ctx = context.WithValue(ctx, oauth2.HTTPClient, httpClient)
```

Every other dependency we use (other than AWS CodeCommit) has reasonable patterns around custom clients. I'm gonna sleep on what to do next, but more than likely it will be having a concrete httpclient which can communicate with external services + some sort of wrapper around our oauth2 usage. (cc @tsenart, @beyang)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
I'm backlogging. This is close though. I switched focussed on more pressing customer issues / the impromptu London Core Services meetup took up my time.

**Comment by keegancsmith** [comment]
Won't get this in before branch cut, but hope to work on it this week.

**Comment by unknwon** [comment]
There is an option `certificate` on GitLab's external service config: https://docs.sourcegraph.com/admin/external_service/gitlab, which could be used to supply a self-signed certificate.

Closing seems it should have been fixed, please comment or reopen if that's not the case!

**Comment by plinss** [comment]
I still have this error with 3.19. The `certificate` option is properly configured and I also tried the `experimentalFeatures/tls.external/certificates` option to no avail.

Please re-open.

It looks like https://github.com/sourcegraph/sourcegraph/pull/8109 which may address this has been closed without merging.

**Comment by plinss** [comment]
FWIW, this issue is preventing our organization from using Sourcegraph.

**Comment by Antoine98** [comment]
> ms it should have been fixed, please comment or reopen if that's not the c

@unknwon the certificate option does not work for Oauth , please reopen the issue

**Comment by keegancsmith** [comment]
Apologies for that, I'll tackle this before we release 3.20 later this month.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by plinss** [comment]
Just tested this with 3.20 and 3.20.1, the original error is no longer happening, but now when trying to login via GitLab I get the error "github: unable to get GitLab user". 

I double-checked the configuration and the auth.providers type is definitely set to 'gitlab', not 'github'. I'm happy to file a new issue if this is something unrelated to the certificate's CA, but guessing it may be related to the fix for this issue.

I also tried deleting and re-creating the OAuth application in GitLab and resetting the Sourcegraph configuration to no avail.

**Comment by unknwon** [comment]
@plinss Thanks for reporting back! Would you mind create a new GitHub issue, it seems something else has gone wrong to me 🤔

**Comment by plinss** [comment]
@unknwon Done. #14144 

Let me know if you need any further info. Or if you'd like me to test anything, I'm happy to help out as I can.

We've been blocked from using Sourcegraph for 9 months due to the CA issue, now that the CA issue is fixed it would be nice to be able to actually use it.
