### ISSUE TITLE
e2e test failures are hard to debug

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#5722]
Yesterday in our 3.9 retrospective we talked about how hard it is to make sense of e2e test failures. To fix that problem we wanted to analyze exactly what makes them hard to debug.

### Example: Login failed in e2e tests

[This build](https://buildkite.com/sourcegraph/sourcegraph/builds/43598#a0be2ad6-0cab-4ff2-a443-2ea58b1edb09) failed because "site admin account was never created because the email field couldn't be found when puppeteer attempted to fill it" ([Slack message](https://sourcegraph.slack.com/archives/C08JA8Q1H/p1569313362016900?thread_ts=1569310435.016500&cid=C08JA8Q1H)).

If you look at the failure you have scroll past **777** lines of browser console log messages that _might_ or _might not_ be related, past tens of screenshots.

Once you get to the errors produced by the test assertions, you can see different reasons:

- `No node found for selector: input[name=email]`
- `Evaluation failed: SyntaxError: Unexpected token P in JSON at position 0`
- `TimeoutError: waiting for selector ".e2e-settings-file .monaco-editor" failed: timeout 30000ms exceeded`
- `TimeoutError: waiting for selector ".e2e-filtered-connection" failed: timeout 30000ms exceeded`
- `TimeoutError: waiting for selector "a[href="/github.com/gorilla/mux"]" failed: timeout 30000ms exceeded`
- `TimeoutError: waiting for selector ".tree__row--active [data-tree-path="godockerize.go"]" failed: timeout 30000ms exceeded`

... and more, spanning **over 3500 lines of log output**

In hindsight, it's easy to tell that the screenshots already point one in the direction of "login failed", but it's not a straightforward way to get to that conclusion if you have JSON parse errors and selector-timeouts intermingled with the rest.

Especially since one would assume that every test depends on the login working and that if the login doesn't work, the rest of the test suite wouldn't run.

**Comment by mrnugget** [comment]
Another example: [e2e tests failed here](https://buildkite.com/sourcegraph/sourcegraph/builds/43602#b5b79405-c46d-408f-8766-c3faea6501b5/76-333) because the Docker container could not be started.

The cause for this first appears on line *333*:

```
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.819829399Z 13:59:25       repo-updater | /bin/sh: exec: line 1: repo-updater: not found
```

Before we come to that line, we come across all sorts of errors and log messages that sound like they could be the cause:

* `[2019-09-24T13:59:24Z] 2019/09/24 13:59:24 socat[530428] E waitpid(): child 530429 exited with status 1`
* `[2019-09-24T13:59:29Z] 2019/09/24 13:59:29 socat[530447] E waitpid(): child 530448 exited with status 1`
* `[2019-09-24T13:59:34Z] 2019/09/24 13:59:34 socat[530423] E waitpid(): child 530464 exited with status 1`

Of course, looking at those now, I see that they're the "symptom" of the Docker container not booting up.

And after the real cause of the issue, there's also this:

```
[2019-09-24T14:00:24Z] ./dev/ci/e2e.sh: line 1: kill: (530423) - No such process
```

And then we also get the whole Docker container output twice:

```
[2019-09-24T14:00:24Z] + docker logs --timestamps 81ac7c10f6581d93ebba6bcfbbb62973ebdc5f5c25a1242468d38ac409a66b16
[2019-09-24T14:00:24Z] 2019-09-24T13:59:23.326903838Z ✱ Sourcegraph is initializing the internal database... (may take 15-20 seconds)
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.819750430Z repo-updater died. Shutting down...
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.819829399Z [0;31m13:59:25       repo-updater | [0m/bin/sh: exec: line 1: repo-updater: not found
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.819854073Z [0;31m13:59:25       repo-updater | [0mTerminating repo-updater
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.820363128Z [0;36m13:59:25        lsif-worker | [0mTerminating lsif-worker
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.820828668Z [0;35m13:59:25  zoekt-indexserver | [0mTerminating zoekt-indexserver
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.821351159Z [0;32m13:59:25              nginx | [0mTerminating nginx
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.821509655Z [0;36m13:59:25       query-runner | [0mTerminating query-runner
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.821896640Z [0;32m13:59:25        lsif-server | [0mTerminating lsif-server
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.822415606Z [0;34m13:59:25           frontend | [0mTerminating frontend
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.822850388Z [0;33m13:59:25    zoekt-webserver | [0mTerminating zoekt-webserver
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.823213925Z [0;33m13:59:25     syntect_server | [0mTerminating syntect_server
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.823598329Z [0;31m13:59:25          gitserver | [0mTerminating gitserver
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824002553Z [0;35m13:59:25       github-proxy | [0mTerminating github-proxy
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824409582Z [0;32m13:59:25 management-console | [0mTerminating management-console
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824526570Z [0;35m13:59:25         prometheus | [0mTerminating prometheus
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824584267Z [0;32m13:59:25            grafana | [0mTerminating grafana
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824590210Z [0;33m13:59:25           searcher | [0mTerminating searcher
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824634702Z [0;34m13:59:25            symbols | [0mTerminating symbols
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824681355Z [0;31m13:59:25        redis-store | [0mTerminating redis-store
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.874633977Z [0;36m13:59:25        redis-cache | [0mTerminating redis-cache
[2019-09-24T14:00:24Z] 2019-09-24T13:59:26.083782181Z [0;34m13:59:26           postgres | [0mTerminating postgres
[2019-09-24T14:00:24Z] + exit 1
[2019-09-24T14:00:24Z] ++ jobs -p
[2019-09-24T14:00:24Z] + kill 530423
[2019-09-24T14:00:24Z] ./dev/ci/e2e.sh: line 1: kill: (530423) - No such process
[2019-09-24T14:00:24Z] + docker logs --timestamps 81ac7c10f6581d93ebba6bcfbbb62973ebdc5f5c25a1242468d38ac409a66b16
[2019-09-24T14:00:24Z] 2019-09-24T13:59:23.326903838Z ✱ Sourcegraph is initializing the internal database... (may take 15-20 seconds)
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.819750430Z repo-updater died. Shutting down...
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.819829399Z [0;31m13:59:25       repo-updater | [0m/bin/sh: exec: line 1: repo-updater: not found
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.819854073Z [0;31m13:59:25       repo-updater | [0mTerminating repo-updater
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.820363128Z [0;36m13:59:25        lsif-worker | [0mTerminating lsif-worker
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.820828668Z [0;35m13:59:25  zoekt-indexserver | [0mTerminating zoekt-indexserver
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.821351159Z [0;32m13:59:25              nginx | [0mTerminating nginx
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.821509655Z [0;36m13:59:25       query-runner | [0mTerminating query-runner
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.821896640Z [0;32m13:59:25        lsif-server | [0mTerminating lsif-server
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.822415606Z [0;34m13:59:25           frontend | [0mTerminating frontend
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.822850388Z [0;33m13:59:25    zoekt-webserver | [0mTerminating zoekt-webserver
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.823213925Z [0;33m13:59:25     syntect_server | [0mTerminating syntect_server
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.823598329Z [0;31m13:59:25          gitserver | [0mTerminating gitserver
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824002553Z [0;35m13:59:25       github-proxy | [0mTerminating github-proxy
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824409582Z [0;32m13:59:25 management-console | [0mTerminating management-console
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824526570Z [0;35m13:59:25         prometheus | [0mTerminating prometheus
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824584267Z [0;32m13:59:25            grafana | [0mTerminating grafana
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824590210Z [0;33m13:59:25           searcher | [0mTerminating searcher
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824634702Z [0;34m13:59:25            symbols | [0mTerminating symbols
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.824681355Z [0;31m13:59:25        redis-store | [0mTerminating redis-store
[2019-09-24T14:00:24Z] 2019-09-24T13:59:25.874633977Z [0;36m13:59:25        redis-cache | [0mTerminating redis-cache
[2019-09-24T14:00:24Z] 2019-09-24T13:59:26.083782181Z [0;34m13:59:26           postgres | [0mTerminating postgres
```

That doesn't help spotting the error

**Comment by felixfbecker** [comment]
Commeenting on the original post (I'll leave the Docker setup to @chrismwendt):

It seems like this was purely caused by two annoying Jest behaviours:
- Jest keeps running the tests even if a `beforeAll` hook failed, which then produce all the noisy test failure logs, screenshots etc
- Jest buffers console messages and prints them all at the top, instead of in between the logs for the test descriptions, which makes browser console logs and screenshots hard to tie to a test

It becomes more clear to me every day that switching to Jest was a mistake (other problems include VS Code debugging not working). @sqs do you have a sense of how much work it would be to migrate back, and what we would _lose_ by doing so?

**Comment by chrismwendt** [comment]
- Logs dumped twice: fixed in https://github.com/sourcegraph/sourcegraph/pull/5732
- "No such process": fixing in https://github.com/sourcegraph/sourcegraph/pull/5733
- socat errors: suppressing these would be easy, but could mask a problem in the future. A better solution would be to expose port 7080 on the dind container which runs the test subject (the Sourcegraph server container).

**Comment by mrnugget** [comment]
Here's another example: https://buildkite.com/sourcegraph/sourcegraph/builds/43747#b2fd9347-df48-4653-91a7-58d22131fa10

The log is full of these messages:

```
Browser console message: ConsoleMessage { _type: 'error', _text: 'JSHandle@error', _args: [ JSHandle { _context: [ExecutionContext], _client: [CDPSession], _remoteObject: [Object], _disposed: false } ], _location: { url: 'http://localhost:7080/.assets/scripts/43-361ffab7c30341c48d00.chunk.js', lineNumber: 0, columnNumber: 59550 } }
```

And these ones here:

```
[2019-09-27T13:35:00Z]     Browser console message: ConsoleMessage { _type: 'error', _text: 'Failed to load resource: the server responded with a status of 500 (Internal Server Error)', _args: [], _location: { url: 'http://localhost:7080/.api/lsif/challenge', lineNumber: undefined } }
```

I still don't know what the actual cause of failure is in that test run.

**Comment by felixfbecker** [comment]
@mrnugget thanks for the report. To debug a test failure, the first thing I look at is **which test failed** and with **what error it failed**. In this case, it is the light theme test (you need to scroll down for this as the test summary is at the bottom, after the logs). I then inspect the code at the stack trace of the error, and see that an assertion is done that is timing-sensitive (no `retry()`/`waitFor*` is used). Opened #5754 with more details.

I agree that the logs can be distracting here, but it is important to not go to the logs first, but always first look at the test failure (and only reach for the logs if more details are needed). The logs are not tied to a specific test (which is tied back to the problem of Jest buffering them) so the majority will not be related to the test that failed. If Jest didn't buffer them, they would be in between the test names, and you'd know which log was done during which test. I am adding this aspect to #5724.

**Comment by mrnugget** [comment]
@felixfbecker Thanks for opening the issue and tracking this down! The approach you described is exactly the one I took, except that I didn't come to the conclusion you came to, because after I saw the failed assertion ("theme switcher didn't pop up? that's probably only a symptom") I looked at the logs and saw that repos were not cloned and that there were a lot of other errors. I then thought that maybe this failure has something to do with the database being slow (something I observered in the past) and that something didn't load properly.

**Comment by felixfbecker** [comment]
Ah, I see. The subtle detail here was that not the theme _switcher_ didn't pop up, but the theme class on the `body` element.

**Comment by mrnugget** [comment]
@keegancsmith reported another really hard to debug E2E test failure in [this comment](https://github.com/sourcegraph/sourcegraph/issues/5721#issuecomment-538079538):

> I have no idea what is going on here. It seems like every test failed, but when you watch the test video it does a lot of stuff. Weird part about the test video is it just waits for a long time on the add external services page without doing anything. https://buildkite.com/sourcegraph/sourcegraph/builds/44147#0034e8b8-9749-4c73-b94b-9ffb4559be2e

**Comment by felixfbecker** [comment]
That sounds like `before` failed to add the external service (some race condition with hitting the save button maybe), and then Jest does it's thing again where it keeps running all the tests despite `before` failing. One more point for #5724.

**Comment by mrnugget** [comment]
Here's another one with a ton of error messages and the test that fails is hover tooltips? Retrying the test fixed it:

https://buildkite.com/sourcegraph/sourcegraph/builds/46055#3340f838-97a6-4435-8317-b47dec906516

(cc @keegancsmith)

**Comment by mrnugget** [comment]
In this e2e run there were 436 (!) `Browser console` log lines: https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/3456#193d383e-428d-4999-bb04-d54615e6122c

413 of them:

```
Browser console: ConsoleMessage { _type: 'log', _text: 'Discarding contributions: evaluating expressions or templates failed. JSHandle@object', _args: [ JSHandle { _context: [ExecutionContext], _client: [CDPSession], _remoteObject: [Object], _disposed: false }, JSHandle { _context: [ExecutionContext], _client: [CDPSession], _remoteObject: [Object], _disposed: false } ], _location: { url: 'http://localhost:7080/.assets/scripts/app.bundle.js?91846ad5e14c162ebeabadb7166095b3', lineNumber: 1, columnNumber: 2301419 } }
```

**Comment by mrnugget** [comment]
Before the cleaning up of the logs and the switch to Mocha, I think we always had a Percy screenshot in the e2e test logs when something failed.

[In this build](https://buildkite.com/sourcegraph/e2e/builds/4105#3b5bc854-8426-4853-8e98-57e8cb090f0c) there are no screenshots and none of the error messages tell me what actually failed:

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/1185253/72895764-78030b00-3d1e-11ea-969b-d9cd3e851560.png">

**Comment by felixfbecker** [comment]
There's some nuance here: There are two different screenshot reporting mechanisms. One that reports to Percy, and one that prints one for inline display in the Buildkite logs.

Both are taken in an `afterEach()` (which runs after each _test_), if the _test_ failed. In the failure you posted though, it wasn't a test that failed, but the "before all" hook, so the screenshot reporters don't run.

What you can still do is go to the artifacts tab and watch the video recording, which shows where the hook got stuck: 
https://buildkite.com/organizations/sourcegraph/pipelines/e2e/builds/4105/jobs/3b5bc854-8426-4853-8e98-57e8cb090f0c/artifacts/9614f7db-c2d3-4079-b019-796406a1cd16

![image](https://user-images.githubusercontent.com/10532611/72896199-7423b880-3d1f-11ea-8d67-995fcbcc9818.png)

**Comment by mrnugget** [comment]
Ahhh! I forgot about the video! Thank you!

**Comment by mrnugget** [comment]
I'm also closing this ticket now due to the numerous improvements you made, @felixfbecker. I think we can always create tickets for more specific "hard to debug" builds then. Reopen if you disagree with this.
