### ISSUE TITLE
new postgres_exporter does not respect custom postgres DB / PG_* env vars

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6735]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2ae951d688309cc223028d391397c65ad34eadd7/-/blob/cmd/server/shared/shared.go#L145:4

Luckily, this does not crash the whole server it just complains, so we can ship this in our next release / patch release:

```
$ docker run -it -e DATA_SOURCE_NAME="postgresql://postgres:sourcegraphd@127.0.0.1:54324/postgres?sslmode=disable" wrouesnel/postgres_exporter:v0.7.0@sha256:785c919627c06f540d515aac88b7966f352403f73e931e70dc2cbf783146a98b 
INFO[0000] Established new database connection to "127.0.0.1:54324".  source="postgres_exporter.go:814"
INFO[0001] Established new database connection to "127.0.0.1:54324".  source="postgres_exporter.go:814"
INFO[0003] Established new database connection to "127.0.0.1:54324".  source="postgres_exporter.go:814"
ERRO[0006] Error opening connection to database (postgresql://postgres:PASSWORD_REMOVED@127.0.0.1:54324/postgres?sslmode=disable): dial tcp 127.0.0.1:54324: connect: connection refused  source="postgres_exporter.go:1403"
INFO[0006] Starting Server: :9187                        source="postgres_exporter.go:1576"
```

**Comment by uwedeportivo** [comment]
oops, got it

will send a fix

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/sourcegraph/pull/6744

**Comment by slimsag** [comment]
We have just received a report from a user indicating there is still an issue here somewhere on at least v3.10. More details to come.

**Comment by sqs** [comment]
Is the problem related to what I fixed (for dev only) in https://github.com/sourcegraph/sourcegraph/pull/7664? The default for PGUSER is `$USER` if it is set, not `sourcegraph` as #6744 hardcodes.

**Comment by uwedeportivo** [comment]
looking at this now and the PR from sqs

**Comment by felixfbecker** [comment]
I am still seeing this continuous log spam in dev:
```
12:18:19   postgres_exporter | time="2020-03-09T11:18:19Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:18:21   postgres_exporter | time="2020-03-09T11:18:21Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:18:24   postgres_exporter | time="2020-03-09T11:18:24Z" level=error msg="Error opening connection to database (postgresql://felix:PASSWORD_REMOVED@/tmp:5432/postgres?sslmode=disable): dial tcp 127.0.0.1:5432: connect: connection refused" source="postgres_exporter.go:1403"
12:18:47   postgres_exporter | time="2020-03-09T11:18:47Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:18:48   postgres_exporter | time="2020-03-09T11:18:48Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:18:50   postgres_exporter | time="2020-03-09T11:18:50Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:18:53   postgres_exporter | time="2020-03-09T11:18:54Z" level=error msg="Error opening connection to database (postgresql://felix:PASSWORD_REMOVED@/tmp:5432/postgres?sslmode=disable): dial tcp 127.0.0.1:5432: connect: connection refused" source="postgres_exporter.go:1403"
12:19:17   postgres_exporter | time="2020-03-09T11:19:17Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:19:18   postgres_exporter | time="2020-03-09T11:19:18Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:19:20   postgres_exporter | time="2020-03-09T11:19:20Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:19:23   postgres_exporter | time="2020-03-09T11:19:23Z" level=error msg="Error opening connection to database (postgresql://felix:PASSWORD_REMOVED@/tmp:5432/postgres?sslmode=disable): dial tcp 127.0.0.1:5432: connect: connection refused" source="postgres_exporter.go:1403"
12:19:47   postgres_exporter | time="2020-03-09T11:19:47Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:19:48   postgres_exporter | time="2020-03-09T11:19:48Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:19:50   postgres_exporter | time="2020-03-09T11:19:50Z" level=info msg="Established new database connection to \"localhost:5432\"." source="postgres_exporter.go:814"
12:19:53   postgres_exporter | time="2020-03-09T11:19:53Z" level=error msg="Error opening connection to database (postgresql://felix:PASSWORD_REMOVED@/tmp:5432/postgres?sslmode=disable): dial tcp 127.0.0.1:5432: connect: connection refused" source="postgres_exporter.go:1403"
```
I have both `PGUSER` and `PGDATABASE` set.
